apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: ""
  manila:
    enabled: true
    template:
      manilaAPI:
        customServiceConfig: |
          [DEFAULT]
          debug = true
          enabled_share_protocols=nfs,cephfs,cifs
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-api:current-tripleo
      manilaScheduler:
        replicas: 1
        containerImage: quay.io/tripleozedcentos9/openstack-manila-scheduler:current-tripleo
      manilaShares:
        share1:
          networkAttachments:
          - storage
          customServiceConfig: |
              [DEFAULT]
              enabled_share_backends=cephfsnfs
              [cephfsnfs]
              driver_handles_share_servers=False
              share_backend_name=cephfs
              share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
              cephfs_auth_id=openstack
              cephfs_cluster_name=ceph
              cephfs_nfs_cluster_id=cephfs
              cephfs_protocol_helper_type=NFS
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
        share2:
          networkAttachments:
          - storage
          customServiceConfig: |
              [DEFAULT]
              enabled_share_backends=cephfs
              [cephfs]
              driver_handles_share_servers=False
              share_backend_name=cephfs
              share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
              cephfs_conf_path=/etc/ceph/ceph.conf
              cephfs_auth_id=openstack
              cephfs_cluster_name=ceph
              cephfs_enable_snapshots=True
              cephfs_ganesha_server_is_remote=False
              cephfs_volume_mode=0755
              cephfs_protocol_helper_type=CEPHFS
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
        share3:
          networkAttachments:
          - storage
          customServiceConfig: |
            [DEFAULT]
            debug = true
            enabled_share_backends=netapp
            [netapp]
            driver_handles_share_servers=False
            share_backend_name=netapp
            share_driver=manila.share.drivers.netapp.common.NetAppDriver
            netapp_storage_family=ontap_cluster
            netapp_transport_type=http
          customServiceConfigSecrets:
            - osp-secret-manila-netapp
          containerImage: quay.io/tripleozedcentos9/openstack-manila-share:current-tripleo
          replicas: 1
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - Manila
          extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-conf-files
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
