apiVersion: manila.openstack.org/v1beta1
kind: Manila
metadata:
  name: manila
  namespace: openstack
spec:
  serviceUser: manila
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  secret: osp-secret
  databaseAccount: manila
  rabbitMqClusterName: rabbitmq
  manilaAPI: {}
  manilaScheduler: {}
  manilaShares:
    share1: {}
